[".oh-my-zsh"]
url = "https://github.com/ohmyzsh/ohmyzsh"
type = "git-repo"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/F-Sy-H"]
url = "https://github.com/z-shell/F-Sy-H.git"
type = "git-repo"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
url = "https://github.com/zsh-users/zsh-autosuggestions"
type = "git-repo"
exact = true
refreshPeriod = "168h"

[".oh-my-zsh/custom/themes/powerlevel10k"]
url = "https://github.com/romkatv/powerlevel10k.git"
type = "git-repo"
exact = true
refreshPeriod = "168h"
clone.args = ["--depth=1"]

[".tmux/plugins/tpm"]
url = "https://github.com/tmux-plugins/tpm"
type = "git-repo"
exact = true
refreshPeriod = "168h"
