#!/bin/sh
#
# ~/.myenv
#
export PATH="$HOME/bin:$HOME/.cargo/bin:$PATH"
export EDITOR="nvim"
export FZF_DEFAULT_COMMAND='fd -L -t f'
export FZF_BASE="/usr/bin/fzf"
export FZF_DEFAULT_OPTS="\
  --color=bg+:#2d3f76 \
  --color=bg:#1e2030 \
  --color=border:#589ed7 \
  --color=fg:#c8d3f5 \
  --color=gutter:#1e2030 \
  --color=header:#ff966c \
  --color=hl+:#65bcff \
  --color=hl:#65bcff \
  --color=info:#545c7e \
  --color=marker:#ff007c \
  --color=pointer:#ff007c \
  --color=prompt:#65bcff \
  --color=query:#c8d3f5:regular \
  --color=scrollbar:#589ed7 \
  --color=separator:#ff966c \
  --color=spinner:#ff007c \
  --highlight-line \
  --layout='reverse' \
  --prompt=' ' \
  --marker='󰃀' \
  --pointer='' \
  --separator='󱋰' \
  --info='right' \
  --border='left' \
  --no-scrollbar \
  --preview='preview {}'
"
# TODO:
# FZF
# CTRL_T CTRL_R ALT_C
# OPTS DEFAULT_COMMAND
