#!/bin/bash
#
# ~/.bashrc
#
[[ $- != *i* ]] && return
[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion

shopt -s checkwinsize
shopt -s expand_aliases
shopt -s histappend

source "$HOME/.myenv"
