{{if false}} vim:filetype=toml.chezmoitmpl {{end}}
{{ with get . .colorscheme }}
[colors.primary]
background = {{ .bg | quote }}
foreground = {{ .fg | quote }}

[colors.cursor]
cursor = {{ .fg | quote }}
text = {{ .bg | quote }}

# Normal colors
[colors.normal]
black = {{ .black | quote }}
red = {{ .red | quote }}
green = {{ .green | quote }}
yellow = {{ .yellow | quote }}
blue = {{ .blue | quote }}
magenta = {{ .magenta | quote }}
cyan = {{ .cyan | quote }}
white = {{ .fg_dark | quote }}

# Bright colors
[colors.bright]
black = {{ .terminal_black | quote }}
red = {{ .red | quote }}
green = {{ .green | quote }}
yellow = {{ .yellow | quote }}
blue = {{ .blue | quote }}
magenta = {{ .magenta | quote }}
cyan = {{ .cyan | quote }}
white = {{ .fg | quote }}

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = {{ .orange | quote }}

[[colors.indexed_colors]]
index = 17
color = {{ .red1 | quote }}
{{- end }}
