#!/bin/zsh

source ~/.profile

export XDG_CONFIG_HOME="$HOME/.config"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$ZDOTDIR/history"
export ZSH="$ZDOTDIR/ohmyzsh"
export ZSH_THEME="nicoulaj"
plugins=(
  chezmoi
  bun
  eza
  fzf
  F-Sy-H
  gh
  git
  postgres
  python
  rust
  tmux
  zsh-autosuggestions
  zoxide
)

source "$ZSH/oh-my-zsh.sh"

[ -d "$ZDOTDIR/config.d/" ] && source <(cat "$ZDOTDIR"/config.d/*)
[ -f "$XDG_CONFIG_HOME/user-dirs.dirs" ] && source "$XDG_CONFIG_HOME/user-dirs.dirs"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
