#!/usr/bin/env sh

status() {
  systemctl --user is-active wluma >/dev/null 2>&1
}

# Accepts managing parameter
case "$1" in
'toggle')
  ~/.local/bin/waybar-signal adaptive-brightness
  status && systemctl --user stop wluma || systemctl --user start wluma
  ;;
'check')
  [ -x "$(command -v wluma)" ] && [ "$(find /sys/class/backlight/ | wc -l)" -gt 0 ]
  exit $?
  ;;
esac

# Returns data for Waybar
if status; then
  class=on
  text="adaptive brightness"
else
  class=off
  text="static brightness"
fi

printf '{"alt":"%s","tooltip":"%s"}\n' "$class" "$text"
