#!/bin/zsh
#
# ~/.zshrc
#

source ~/.profile

ZSH_THEME="random"
plugins=(
  alias-finder
  eza
  fzf
  F-Sy-H
  git
  poetry
  python
  rust
  tmux
  zsh-autosuggestions
  zoxide
)

[ -d /usr/share/oh-my-zsh ] && source /usr/share/oh-my-zsh/zshrc
[ -d ~/.config/zsh/config.d/ ] && source <(cat ~/.config/zsh/config.d/*)
[ -f ~/.config/user-dirs.dirs ] && source ~/.config/user-dirs.dirs

zstyle ':omz:plugins:alias-finder' autoload yes
zstyle ':omz:plugins:alias-finder' longer yes
zstyle ':omz:plugins:alias-finder' exact yes
zstyle ':omz:plugins:alias-finder' cheaper yes

