import = ["~/.config/alacritty/themes/tokyonight_moon.toml"]
[env]
[window]
# "Full" | "None"
decorations = "None"
# "Windowed" | "Maximized" | "Fullscreen"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 10
